Lab/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('Reception.urls','mml'),namespace='mml')),
    path('news/',include(('news.urls','news'),namespace='news')),
    path('primarystation/',include(('primarystation.urls','pst'),namespace='pst')),
    path('papers/',include(('papers.urls','papers'),namespace='papers')),
]
urlpatterns += staticfiles_urlpatterns()

Reception/urls.py
from django.conf.urls import url
from django.urls import  include,path
from Reception import views
app_name="mml"
urlpatterns = [
    path('courses/',views.courses,name='courses'),
    path('members/',views.members,name='members'),
    path('layout/',views.layout,name='layout'),
    path('index/',views.index,name='index'),
    path('',views.toIndex),
    path('news/',include(('news.urls','news'),namespace='news')),

]

news/urls.py
from django.urls import path
from news import views
app_name='news'
urlpatterns = [
    path('',views.toIndex),
    path('index/',views.index,name="index"),
    path('list/',views.list,name='list'),
    path('article/',views.article,name='article'),

]

papers/urls.py
from django.urls import  include,path
from papers import views
app_name="papers"
urlpatterns = [
    path('',views.toIndex),
    path('index/',views.index,name='index'),



]

primarystation/urls.py
from django.urls import  include,path
from primarystation import views
app_name="pst"
urlpatterns = [
    path('',views.toIndex),
    path('base/',views.base,name='base'),
    path('index/',views.index,name='index'),
    path('whisper/',views.whisper,name='whisper'),
    path('me/',views.me,name='me'),
    path('album/',views.album,name='album'),
    path('leacots/',views.leacots,name='leacots'),


]

Reception/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models

# Create your models here.

papers/models.py
from django.db import models

# Create your models here.

primarystation/models.py
from django.db import models

# Create your models here.

Reception/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.
def index(request):
    #return HttpResponse("hello world")
    return render(request,"mml/index.html",{})
def toIndex(request):
    return HttpResponseRedirect(reverse("mml:index"))
def members(requset):
    return render(requset,'mml/members.html',{})
def courses(request):
    return render(request,'mml/courses.html',{})
def services(request):
    return render(request,'mml/services.html',{})
def icons(request):
    return render(request,'mml/icons.html',{})
def mail(request):
    return render(request,'mml/mail.html',{})
def typography(request):
    return render(request,'mml/typography.html',{})
def layout(request):
    return render(request, 'mml/../templates/layout.html', {})
def news(request):
    return render(request,'mml/news.html',{})

news/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

app_name="news"
def toIndex(request):
    return HttpResponseRedirect(reverse("news:index"))
def index(request):
    return render(request,'news/index.html',{})
def list(request):
    return render(request,'news/list.html')
def article(request):
    return render(request,'news/article.html')

papers/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse


def toIndex(request):
    return HttpResponseRedirect(reverse('papers:index'))
def index(request):
    return render(request,'papers/index.html',{})

primarystation/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse


def toIndex(request):
    return HttpResponseRedirect(reverse("pst:index"))
def index(request):
    return render(request,'pst/index.html',{})
def whisper(request):
    return render(request,'pst/whisper.html',{})
def leacots(request):
    return render(request,'pst/leacots.html',{})
def album(request):
    return render(request,'pst/album.html',{})
def me(request):
    return render(request,'pst/about.html',{})
def details(request):
    return render(request,'pst/details.html',{})
def base(request):
    return render(request,'pst/base.html',{})

templates/layout.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title%}</title>
<!-- custom-theme -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //custom-theme -->
{% block addHead %}
{%endblock addHead  %}
{% block replaceHead %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!-- js -->
    <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <!-- //js -->
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" property="" />
    <!-- gallery -->
    <link href="{% static 'css/lsb.css' %}" rel="stylesheet" type="text/css">
    <!-- //gallery -->
    <!-- font-awesome-icons -->
    <link href="{%static 'css/font-awesome.css' %}" rel="stylesheet">

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'icon/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'icon/favicon.ico' %}" type="image/x-icon">
{% endblock replaceHead%}
<!-- //font-awesome-icons
<link href="http://fonts.googleapis.com/css?family=Prompt:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,thai,vietnamese" rel="stylesheet"></head>
-->
{% block appendHead %}
{% endblock appendHead %}
<body  style='overflow:-Scroll;overflow-x:hidden'>
<!-- banner -->
	<div class="banner1">
		<nav class="navbar navbar-default">
			<div class="navbar-header navbar-left">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<h1><a class="navbar-brand" href="{%url 'mml:index'%}"><span>MML</span>多媒体实验室</a></h1>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
				<nav class="link-effect-2" id="link-effect-2">
					<ul class="nav navbar-nav">
						<li id="index"><a href="{%url 'mml:index'%}"><span data-hover="首页">首页</span></a></li>
						<li id="members"><a href="{%url 'mml:members' %}"><span data-hover="实验室成员">实验室成员</span></a></li>
						<li id="news"><a href="{% url 'news:index' %}"><span data-hover="新闻通知">新闻通知</span></a></li>
						<li class="dropdown">
							<a  href="#" class="dropdown-toggle" data-toggle="dropdown"><span id="research" data-hover="科研工作">科研工作</span> <b class="caret"></b></a>
							<ul class="dropdown-menu agile_short_dropdown">
								<li><a href="{% url 'papers:index' %}">论文</a></li>
								<li><a href="">项目</a></li>
							</ul>
						</li>
						<li><a href="mail"><span data-hover="Mail Us">Mail Us</span></a></li>
					</ul>
				</nav>
			</div>
			<div class="w3_agile_phone">
				<p><i class="fa fa-phone" aria-hidden="true"></i> mail:nianhao@ouc.edu.cn</p>
			</div>
		</nav>
	</div>
<div>
{% block main %}
{% endblock main %}
</div>

<!-- footer -->
	<div class="footer">
		<div class="container">
			<div class="agile_footer_copy">
				<div class="w3agile_footer_grids">
					<div class="col-md-4 w3agile_footer_grid">
						<h3>About Us</h3>
						<p>Duis aute irure dolor in reprehenderit in voluptate velit esse.<span>Excepteur sint occaecat cupidatat
							non proident, sunt in culpa qui officia deserunt mollit.</span></p>
					</div>
					<div class="col-md-4 w3agile_footer_grid">
						<h3>Contact Info</h3>
						<ul>
							<li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>1234k Avenue, 4th block, <span>New York City.</span></li>
							<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
							<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>+1234 567 567</li>
						</ul>
					</div>
					<div class="col-md-4 w3agile_footer_grid w3agile_footer_grid1">
						<h3>Navigation</h3>
						<ul>
							<li><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span><a href="{% url 'mml:members' %}">实验室成员</a></li>
							<li><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span><a href="{% url 'news:index' %}">新闻通知</a></li>
							<li><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span><a href="icons">Web Icons</a></li>
							<li><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span><a href="mail">Mail Us</a></li>
						</ul>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
			<div class="w3_agileits_copy_right_social">
				<div class="col-md-6 agileits_w3layouts_copy_right">
					<p>Copyright &copy; 2017.Company name All rights reserved.</p>
				</div>
				<div class="col-md-6 w3_agile_copy_right">
					<ul class="agileinfo_social_icons">
						<li><a href="#" class="w3_agileits_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" class="wthree_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#" class="agileinfo_google"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
						<li><a href="#" class="agileits_pinterest"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //footer -->
{% block footer %}
{% endblock footer %}
<!-- carousal -->
	<script src="/static/js/slick.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript">
		$(document).on('ready', function() {
		  $(".center").slick({
			dots: true,
			infinite: true,
			centerMode: true,
			slidesToShow: 2,
			slidesToScroll: 2,
			responsive: [
				{
				  breakpoint: 768,
				  settings: {
					arrows: true,
					centerMode: false,
					slidesToShow: 2
				  }
				},
				{
				  breakpoint: 480,
				  settings: {
					arrows: true,
					centerMode: false,
					centerPadding: '40px',
					slidesToShow: 1
				  }
				}
			 ]
		  });
		});
	</script>
<!-- //carousal -->
<!-- flexisel -->
		<script type="text/javascript">
		$(window).load(function() {
			$("#flexiselDemo1").flexisel({
				visibleItems: 4,
				animationSpeed: 1000,
				autoPlay: true,
				autoPlaySpeed: 3000,
				pauseOnHover: true,
				enableResponsiveBreakpoints: true,
				responsiveBreakpoints: {
					portrait: {
						changePoint:480,
						visibleItems: 1
					},
					landscape: {
						changePoint:640,
						visibleItems:2
					},
					tablet: {
						changePoint:768,
						visibleItems: 2
					}
				}
			});

		});
	</script>
	<script type="text/javascript" src="{% static 'js/jquery.flexisel.js' %}"></script>
<!-- //flexisel -->
<!-- gallery-pop-up -->
	<script src="{% static 'js/lsb.min.js' %}"></script>
	<script>
	$(window).load(function() {
		  $.fn.lightspeedBox();
		});
	</script>
<!-- //gallery-pop-up -->
<!-- flexSlider -->
	<script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
	<script type="text/javascript">
		$(window).load(function(){
		  $('.flexslider').flexslider({
			animation: "slide",
			start: function(slider){
			  $('body').removeClass('loading');
			}
		  });
		});
	</script>
<!-- //flexSlider -->
{#<!-- banner-type-text -->#}
{#	<script src="{% static 'js/typed.js' %}" type="text/javascript"></script>#}
{#    <script>#}
{#		$(function(){#}
{##}
{#			$("#typed").typed({#}
{#				// strings: ["Typed.js is a <strong>jQuery</strong> plugin.", "It <em>types</em> out sentences.", "And then deletes them.", "Try it out!"],#}
{#				stringsElement: $('#typed-strings'),#}
{#				typeSpeed: 30,#}
{#				backDelay: 500,#}
{#				loop: true,#}
{#				contentType: 'html', // or text#}
{#				// defaults to false for infinite loop#}
{#				loopCount: false,#}
{#				callback: function(){ foo(); },#}
{#				resetCallback: function() { newTyped(); }#}
{#			});#}
{##}
{#			$(".reset").click(function(){#}
{#				$("#typed").typed('reset');#}
{#			});#}
{##}
{#		});#}
{##}
{#		function newTyped(){ /* A new typed object */ }#}
{##}
{#		function foo(){ console.log("Callback"); }#}
{#    </script>#}
<!-- //banner-type-text -->
<!-- start-smooth-scrolling -->
<script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>
<!-- start-smooth-scrolling -->
<!-- for bootstrap working -->
	<script src="{% static 'js/bootstrap.js' %}"></script>
<!-- //for bootstrap working -->
<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
			*/

			$().UItoTop({ easingType: 'easeOutQuart' });

			});
    //解决首页超链接不能点击的bug
       /* $("a").click(function (obj) {
            obj.disabled();
        })*/
	</script>
<!-- //here ends scrolling icon -->
</body>
</html>

templates/mml/members.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% block title %}实验室成员{% endblock title %}
{% block addHead %}
<!-- Google fonts
<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
-->
<!-- font awesome -->
{#<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">#}
<!-- bootstrap
<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" />-->
<!-- animate.css -->
<link rel="stylesheet" href="{% static 'assets/animate/animate.css' %}" />
<link rel="stylesheet" href="{% static 'assets/animate/set.css' %}" />
<!-- gallery -->
<link rel="stylesheet" href="{% static 'assets/gallery/blueimp-gallery.min.cs' %}s">
<link rel="stylesheet" href="{% static 'assets/style.css' %}">

{% endblock addHead%}
{% block main %}

<!--介绍-->
<div class="container">
    <div class="col-md-6 w3ls_banner_bottom_left">
        <div class="w3ls_banner_bottom_left1">
            <p>01</p>
            <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
        </div>
        <div class="w3ls_banner_bottom_right1">
            <h2>研究生<span>2018级</span></h2>
            <p>Pellentesque convallis diam consequat magna vulputate malesuada.
                Cras a ornare elit. Nulla viverra pharetra sem, eget pulvinar neque pharetra ac.</p>
        </div>
        <div class="clearfix"> </div>
    </div>
    <div class="clearfix"> </div>
</div>
<!-- works 具体成员-->
<div id="works"  class=" clearfix grid"> 
    <!--<figure class="effect-oscar  wowload fadeIn">
        <img src="/static/images/portfolio/1.jpg" alt="img01"/>
        <figcaption>
            <h2>Nature</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/1.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>-->
     <figure class="effect-oscar  wowload fadeInUp">
        <img src="/static/images/portfolio/2.jpg" alt="img01"/>
        <figcaption>
            <h2>Events</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/2.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>
     <figure class="effect-oscar  wowload fadeInUp">
        <img src="/static/images/portfolio/3.jpg" alt="img01"/>
        <figcaption>
            <h2>music</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/3.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>
     <figure class="effect-oscar  wowload fadeInUp">
        <img src="/static/images/portfolio/4.jpg" alt="img01"/>
        <figcaption>
            <h2>Vintage</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/4.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>
     <figure class="effect-oscar  wowload fadeInUp">
        <img src="/static/images/portfolio/5.jpg" alt="img01"/>
        <figcaption>
            <h2>Typers</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/5.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>
     
     <figure class="effect-oscar  wowload fadeInUp">
        <img src="/static/images/portfolio/6.jpg" alt="img01"/>
        <figcaption>
            <h2>hotel</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/6.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>
    <figure class="effect-oscar  wowload fadeInUp">
        <img src="/static/images/portfolio/7.jpg" alt="img01"/>
        <figcaption>
            <h2>Chinese</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/7.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>
    <figure class="effect-oscar  wowload fadeInUp">
        <img src="/static/images/portfolio/8.jpg" alt="img01"/>
        <figcaption>
            <h2>Dicrap</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/8.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>
    <figure class="effect-oscar  wowload fadeInUp">
        <img src="/static/images/portfolio/9.jpg" alt="img01"/>
        <figcaption>
            <h2>Coffee</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/9.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>
    <figure class="effect-oscar  wowload fadeInUp">
        <img src="/static/images/portfolio/10.jpg" alt="img01"/>
        <figcaption>
            <h2>cameras</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/10.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>
    <figure class="effect-oscar  wowload fadeInUp">
        <img src="/static/images/portfolio/11.jpg" alt="img01"/>
        <figcaption>
            <h2>design</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/11.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>
    <figure class="effect-oscar  wowload fadeInUp">
        <img src="/static/images/portfolio/12.jpg" alt="img01"/>
        <figcaption>
            <h2>studio</h2>
            <p>Lily likes to play with crayons and pencils<br>
            <a href="/static/images/portfolio/12.jpg" title="1" data-gallery>View more</a></p>
        </figcaption>
    </figure>
    

     
</div>
<!-- works -->



<!-- team -->
<h3 class="text-center  wowload fadeInUp">Our team</h3>
<p class="text-center  wowload fadeInLeft">Our creative team that is making everything possible</p>
<div class="row grid team  wowload fadeInUpBig">	
	<div class=" col-sm-3 col-xs-6">
	<figure class="effect-chico">
        <img src="/static/images/team/8.jpg" alt="img01" class="img-responsive" />
        <figcaption>
            <p><b>Barbara Husto</b><br>Senior Designer<br><br><a href="#"><i class="fa fa-dribbble"></i></a> <a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a></p>            
        </figcaption>
    </figure>
    </div>

    <div class=" col-sm-3 col-xs-6">
	<figure class="effect-chico">
        <img src="/static/images/team/10.jpg" alt="img01"/>
        <figcaption>            
            <p><b>Barbara Husto</b><br>Senior Designer<br><br><a href="#"><i class="fa fa-dribbble"></i></a> <a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a></p>            
        </figcaption>
    </figure>
    </div>

    <div class=" col-sm-3 col-xs-6">
	<figure class="effect-chico">
        <img src="/static/images/team/12.jpg" alt="img01"/>
        <figcaption>
            <p><b>Barbara Husto</b><br>Senior Designer<br><br><a href="#"><i class="fa fa-dribbble"></i></a> <a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a></p>          
        </figcaption>
    </figure>
    </div>

    <div class=" col-sm-3 col-xs-6">
	<figure class="effect-chico">
        <img src="/static/images/team/17.jpg" alt="img01"/>
        <figcaption>
            <p><b>Barbara Husto</b><br>Senior Designer<br><br><a href="#"><i class="fa fa-dribbble"></i></a> <a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a></p>
        </figcaption>
    </figure>
    </div>

 
</div>
{% endblock main %}
<!-- team -->
{% block footer %}
<!-- jquery
<script src="{% static 'assets/jquery.js'%}"></script>-->
<!-- wow script -->
<script src="{% static 'assets/wow/wow.min.js' %}"></script>
<!-- boostrap
<script src="{% static 'assets/bootstrap/js/bootstrap.js' %}" type="text/javascript" ></script>-->
<!-- jquery mobile -->
<script src="{% static 'assets/mobile/touchSwipe.min.js' %}"></script>
<script src="{% static 'assets/respond/respond.js' %}"></script>
<!-- gallery -->
<script src="{% static 'assets/gallery/jquery.blueimp-gallery.min.js' %}"></script>
<!-- custom script
<script src="{% static 'assets/script.js' %}"></script>-->
<!--使本页为活动页-->
<script type="text/javascript">
    $("#members").addClass("active");
</script>
{% endblock footer%}

templates/pst/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'pst/layui/css/layui.css' %}/">
    <link rel="stylesheet" type="text/css" href="{% static 'pst/css/main.css' %}">
    <script src="{% static 'js/jquery-2.1.4.min.js'%}"></script>
    <!--加载meta IE兼容文件-->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="header">
        <div class="menu-btn">
          <div class="menu"></div>
        </div>
        <h1 class="logo">
            <a href="index.html">
                <span>MYBLOG</span>
                <img src="{% static 'pst/img/logo.png' %}">
            </a>
        </h1>
        <div class="nav">
            <a href="{% url 'pst:index' %}" name="index">首页</a>
            <a href="{% url 'pst:whisper' %}" name="whisper">微语</a>
            <a href="{% url 'pst:leacots' %}" name="leacots">留言</a>
            <a href="{% url 'pst:album' %}" name="album">相册</a>
            <a href="{% url 'pst:me' %}" name="me">博主</a>
        </div>
        <ul class="layui-nav header-down-nav">
            <li class="layui-nav-item"><a href="{% url 'pst:index' %}" name="index">首页</a></li>
            <li class="layui-nav-item"><a href="{% url 'pst:whisper' %}" name="whisper">微语</a></li>
            <li class="layui-nav-item"><a href="{% url 'pst:leacots' %}" name="leacots">留言</a></li>
            <li class="layui-nav-item"><a href="{% url 'pst:album' %}" name="album">相册</a></li>
            <li class="layui-nav-item"><a href="{% url 'pst:me' %}" name="me">博主</a></li>
        </ul>
        <p class="welcome-text">
          欢迎来到<span class="name">小明</span>的博客~
        </p>
    </div>


    {% block main %}
    {% endblock main %}


    <div class="footer-wrap">
        <div class="footer w1000">
            <div class="qrcode">
                <img src="{% static 'pst/img/erweima.jpg' %}">
            </div>
            <div class="practice-mode">
                <img src="{% static 'pst/img/down_img.jpg' %}">
                <div class="text">
                    <h4 class="title">我的联系方式</h4>
                    <p>微信<span class="WeChat">1234567890</span></p>
                    <p>邮箱<span class="email">1234567890@qq.com</span></p>
                    <p>More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
                </div>
            </div>
        </div>
  </div>
 {% block footer_script %}
  <script type="text/javascript" src="{% static 'pst/layui/layui.js' %}"></script>
  <script type="text/javascript">
   layui.config({
      base: "{% static 'pst/js/util/' %}"
    }).use(['element','laypage','form','menu'],function(){
      element = layui.element,laypage = layui.laypage,form = layui.form,menu = layui.menu;
      laypage.render({
        elem: 'demo'
        ,count: 70 //数据总数，从服务端得到
      });
      menu.init();
      menu.submit()
    })
  </script>
  {% endblock footer_script %}
</body>
</html>